config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('darts.urls', namespace='darts')),
    path('players/', include('users.urls')),

    path('__debug__/', include("debug_toolbar.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

darts/urls.py
from django.urls import path

from . import views
from .views import LeagueTableView, WinCreateView, AllGamesView, AllResults, SubmitGameView

app_name = 'darts'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('all-games/', AllResults.as_view(), name='all_games'),
    path('submit-game/', SubmitGameView.as_view(), name='submit_game'),
    path('wrapped/<int:year>/', views.wrapped, name='wrapped'),

    # Old URLs
    path('old/', LeagueTableView.as_view(), name='dashboard_old'),
    path('old/all-games/', AllGamesView.as_view(), name='all_games_old'),
    path('old/submit-win/', WinCreateView.as_view(), name='submit_win_old'),
]

darts/models.py
import datetime

from django.db import models
from django.conf import settings

class Win(models.Model):
    date = models.DateField(auto_now_add=False, default=datetime.date.today)
    winner =  models.ForeignKey(settings.AUTH_USER_MODEL, to_field='id', on_delete=models.CASCADE, related_name='wins')
    runner_up = models.ForeignKey(settings.AUTH_USER_MODEL, to_field='id', on_delete=models.CASCADE, related_name='runner_ups')
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="games_played")

    class Meta:
        indexes = [
            models.Index(fields=['id'], name='win_id_index'),
        ]

    def __str__(self):
        return str(self.date)
    
    def get_this_years_games_count(self):
        return Win.objects.filter(date__contains=datetime.date.today().year).count()
    
class Bet(models.Model):
    description = models.CharField(max_length=255)

    def __str__(self):
        return str(self.description)
    
class Champion(models.Model):
    year = models.DateField()
    user =  models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="championships")
    wins = models.IntegerField()

    def __str__(self):
        return str(self.year.year)

darts/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.timezone import now

from users.models import CustomUser
from .models import Win

class WinCreateForm(forms.ModelForm):
    winner = forms.ModelChoiceField(
        queryset=CustomUser.objects.exclude(plays_darts=False),
        required=True
    )
    runner_up = forms.ModelChoiceField(
        queryset=CustomUser.objects.exclude(plays_darts=False),
        required=True
    )
    participants = forms.ModelMultipleChoiceField(
        queryset=CustomUser.objects.exclude(plays_darts=False),
        widget=forms.CheckboxSelectMultiple(),
        label="All Participants",
        required=True
    )

    class Meta:
        model = Win
        fields = ['winner', 'runner_up', 'participants']

    def clean(self):
        # Overall Form Validation
        cleaned_data = super().clean()
        winner = cleaned_data.get('winner')
        runner_up = cleaned_data.get('runner_up')
        participants = cleaned_data.get('participants')

        if not participants:
            raise ValidationError('You obviously need to add participants you weapon!')

        # 1. The winner and runner up can't be the same
        if winner and runner_up and winner == runner_up:
            raise ValidationError('The winner and runner up have to be different people you donut!')

        # 2. Winner and runner up must be selected as participants
        if winner and winner not in participants:
            raise ValidationError('What are you doing? Include the winner in the participants!')

        if runner_up and runner_up not in participants:
            raise ValidationError('What are you doing? Include the runner up in the participants!')

        # 3. At least 3 participants must be selected
        if participants and len(participants) < 3:
            raise ValidationError('Stop trying to get an easy point Bray. There has to be at least 3 people in a game!')

        #4 Only one submission can be done per day
        if Win.objects.filter(date=now().date()).exists():
            raise ValidationError('A game has already been submitted today. Pay attention you wet wipe!')

        return cleaned_data

darts/views.py
import datetime

from django.template.response import TemplateResponse
from django.views.generic import ListView, CreateView
from django.db.models import Count, Max, Q
from django.urls import reverse

from users.models import CustomUser
from .models import Win, Bet
from .forms import WinCreateForm

# New Views
def dashboard(request):
    # Set Up Sessions Framework & Increment for every request
    visit_count = request.session.get('visit_count', 0)
    request.session['visit_count'] = visit_count + 1

    # Set up Leaderboard & Retrieve Players
    players = CustomUser.objects.exclude(plays_darts=False).annotate(num_wins=Count('wins', filter=Q(wins__date__year=datetime.date.today().year), distinct=True), num_runner_ups=Count('runner_ups', filter=Q(wins__date__year=datetime.date.today().year), distinct=True), last_win=Max('wins__date'), last_runner_up=Max('runner_ups__date'), num_games_played=Count('games_played', filter=Q(wins__date__year=datetime.date.today().year), distinct=True)).order_by('-num_wins', 'last_win', '-num_runner_ups', 'last_runner_up', '-num_games_played', 'first_name', 'last_name').distinct()

    # Retrieve Other Stats
    monthly_leaders = (
        CustomUser.objects.exclude(plays_darts=False)
        .annotate(
            num_wins=Count('wins', filter=Q(wins__date__year=datetime.date.today().year) & Q(wins__date__month=datetime.date.today().month)),
            last_win=Max('wins__date', filter=Q(wins__date__year=datetime.date.today().year) & Q(wins__date__month=datetime.date.today().month))
        )
        .filter(num_wins__gt=0)
        .order_by('-num_wins', 'last_win')
        [:3]
    )

    weekly_leaders = (
        CustomUser.objects.exclude(plays_darts=False)
        .annotate(
            num_wins=Count('wins', filter=Q(wins__date__year=datetime.date.today().year) & Q(wins__date__week=datetime.date.today().isocalendar()[1])),
            last_win=Max('wins__date', filter=Q(wins__date__year=datetime.date.today().year) & Q(wins__date__week=datetime.date.today().isocalendar()[1]))
        )
        .filter(num_wins__gt=0)
        .order_by('-num_wins', 'last_win')
        [:3]
    )

    this_years_game_count = Win.objects.filter(date__contains=datetime.date.today().year).count()

    this_years_player_count = 0
    total_players = CustomUser.objects.all()

    for player in total_players:
        games_played = player.get_this_years_games_played()
        this_years_player_count += games_played

    last_result = Win.objects.latest('date')

    top_5_form = sorted (
        CustomUser.objects.exclude(plays_darts=False)
        .filter(Q(wins__date__year=datetime.date.today().year) | Q(runner_ups__date__year=datetime.date.today().year))
        .distinct(),
        key=lambda u: u.get_form_score(),
        reverse=True
    )[:5]

    top_5_win_ratio = sorted(
        CustomUser.objects.exclude(plays_darts=False)
        .filter(wins__date__year=datetime.date.today().year)
        .distinct(),
        key=lambda u: u.get_win_ratio(),
        reverse=True
    )[:5]

    # Set up Context
    context = {
        'visit_count': visit_count,
        'players': players,
        'monthly_leaders': monthly_leaders,
        'weekly_leaders': weekly_leaders,
        'this_years_game_count': this_years_game_count,
        'this_years_player_count': this_years_player_count,
        'last_result': last_result,
        'top_5_form': top_5_form,
        'top_5_win_ratio': top_5_win_ratio,
    }
    
    return TemplateResponse(request, 'darts/dashboard.html', context)

class AllResults(ListView):
    model = Win
    ordering = ['-date']
    template_name = 'darts/all_results.html'
    context_object_name = 'all_games'
    paginate_by = 30

class SubmitGameView(CreateView):
    model = Win
    template_name = 'darts/submit_game.html'
    form_class = WinCreateForm

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        # Add in custom QuerySets
        context["last_result"] = Win.objects.order_by('-date')[:1]

        # Return context
        return context

    def get_success_url(self):
        return reverse('darts:dashboard')

# Old Views
class LeagueTableView(ListView):
    model = CustomUser
    template_name = 'darts/old/dashboard.html'
    context_object_name = 'players'
    
    def get_queryset(self):
        #return CustomUser.objects.exclude(plays_darts=False).annotate(num_wins=Count('wins', distinct=True), last_win=Max('wins__date')).order_by('-num_wins', 'last_win').distinct()
    
        return CustomUser.objects.exclude(plays_darts=False).annotate(num_wins=Count('wins', distinct=True), num_runner_ups=Count('runner_ups', distinct=True), last_win=Max('wins__date'), last_runner_up=Max('runner_ups__date'), num_games_played=Count('games_played', distinct=True)).order_by('-num_wins', 'last_win', '-num_runner_ups', 'last_runner_up', '-num_games_played', 'first_name', 'last_name').distinct()
    
    def get(self, request, *args, **kwargs):
        # Call the base implementation
        get = super().get(request, *args, **kwargs)

        # Set Up Sessions Framework
        visit_count = request.session.get('visit_count', 0)
        request.session['visit_count'] = visit_count + 1

        # Return Get
        return get

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        
        # Add in custom QuerySets
        context["monthly_leaders"] = CustomUser.objects.exclude(plays_darts=False).annotate(num_wins=Count('wins'), last_win=Max('wins__date')).filter(wins__date__month=datetime.date.today().month).order_by('-num_wins', 'last_win').distinct()[:3]

        context["weekly_leaders"] = CustomUser.objects.exclude(plays_darts=False).annotate(num_wins=Count('wins'), last_win=Max('wins__date')).filter(wins__date__week=datetime.date.today().isocalendar()[1]).order_by('-num_wins', 'last_win').distinct()[:3]

        context["this_years_game_count"] = Win.objects.filter(date__contains=datetime.date.today().year).count()

        context["last_result"] = Win.objects.order_by('-date')[:1]

        context["top_5_form"] = sorted( CustomUser.objects.exclude(plays_darts=False), key=lambda u: u.get_form_score(), reverse=True )[:5]
        context["top_5_win_ratio"] = sorted( CustomUser.objects.exclude(plays_darts=False), key=lambda u: u.get_win_ratio(), reverse=True )[:5]
        
        # Return context
        return context
    
class WinCreateView(CreateView):
    model = Win
    fields = ['winner', 'runner_up', 'participants']
    template_name = 'darts/old/create_win.html'
    form = WinCreateForm

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        
        # Add in custom QuerySets
        context["last_result"] = Win.objects.order_by('-date')[:1]
        
        # Return context
        return context
    
    def get_success_url(self):
        return reverse('darts:dashboard')
    
class AllGamesView(ListView):
    model = Win
    ordering = ['-date']
    template_name = 'darts/old/all_games.html'
    context_object_name = 'all_games'
    paginate_by = 30

def wrapped(request, year):

    context = {
        'year': year
    }

    return TemplateResponse(request, 'darts/wrapped.html', context)

templates/darts/old/_base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'images/favicon.png' %}">
        <link rel="stylesheet" href="{% static 'css/old/style.css' %}">
        <title>{% block title %}Darts Portal{% endblock title %}</title>
    </head>
    <body>
        <div class="nav">
            <div class="primary-container">
                <div class="flex-wrapper">
                    <a href="{% url 'darts:dashboard' %}" class="logo" title="Home">
                        <img src="{% static 'images/logo.png' %}" alt="Pixel Kicks">
                    </a>
                    <ul class="menu">
                        <li><a href="{% url 'darts:dashboard_old' %}" title="Leaderboard">Killer Leaderboard</a></li>
                        <li><a href="{% url 'darts:all_games_old' %}" title="All Results">All Results</a></li>
                    </ul>
                </div>
            </div>
        </div>
        {% block hero %}{% endblock hero %}
        <div class="primary-container">
            <div id="main">
                {% block content %}{% endblock content %}
            </div>

            <script src="{% static 'js/script.js' %}"></script>
            {% block scripts %}{% endblock scripts %}
        </div>
    </body>
</html>

templates/darts/old/all_games.html
{% extends 'darts/old/_base.html' %}

{% block title %}Darts Portal | All Killer Results{% endblock title %}

{% block content %}
    <div class="title-section">
        <h1>All Killer Results</h1>
    </div>

    <div class="all-games">
        <table>
            <thead>
                <tr>
                    <th>
                        <h3>Date</h3>
                    </th>
                    <th>
                        <h3>Winner</h3>
                    </th>
                    <th>
                        <h3>Runner Up</h3>
                    </th>
                    <th class="align-left">
                        <h3>Losers</h3>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for game in all_games %}
                    <tr>
                        <td class="narrow"><p>{{ game.date|date:"D d M" }}</p></td>
                        <td class="narrow"><p>{{ game.winner.first_name }} {{ game.winner.last_name }}</p></td>
                        <td class="narrow"><p>{{ game.runner_up.first_name }} {{ game.runner_up.last_name }}</p></td>
                        <td class="align-left">
                            <p>
                                {% for loser in game.participants.all %}
                                    {% if loser.pk != game.winner.pk and loser.pk != game.runner_up.pk %}
                                        <span>{{ loser.first_name }} {{ loser.last_name }}, </span>
                                    {% endif %}
                                {% endfor %}
                            </p>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

{% endblock content %}

templates/darts/old/create_win.html
{% extends 'darts/old/_base.html' %}

{% block title %}Darts Portal | Submit a Game{% endblock title %}

{% block content %}
    <div class="title-section">
        <h1>Submit a Game</h1>
        <p>Last game submitted on: {{ last_result.0.date|date:"l j F Y" }}</p>
    </div>
    <section class="win-form pk-border">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="button" value="Save">
        </form>
    </section>
{% endblock content %}

templates/darts/old/dashboard.html
{% extends 'darts/old/_base.html' %}

{% block title %}Darts Portal{% endblock title %}

{% block content %}
    <div class="title-section">
        <h1>Killer Darts Leaderboard</h1>
        <div class="buttons">
            <a href="{% url 'darts:submit_win_old' %}" class="button" title="Submit Win">Submit a Game</a>
        </div>
    </div>

    <div class="killer-stats">
        <div class="pk-border">
            <h3>{{ last_result.0.date|date:"l j F" }}</h3>
            <div class="flex-wrapper">
                <div class="global-stats-container">
                    <p>Winner: <span>{{ last_result.0.winner.first_name }} {{ last_result.0.winner.last_name }}</span></p>
                    <p>Runner Up: <span>{{ last_result.0.runner_up.first_name }} {{ last_result.0.runner_up.last_name }}</span></p>
                </div>
            </div>
        </div>
        <div class="pk-border">
            <h3>Current Form</h3>
            <div class="flex-wrapper">
                <div class="global-stats-container">
                    {% for player in top_5_form %}
                        <p>{{ player.first_name }} {{ player.last_name }}: <span>{{ player.get_form_score|floatformat:1 }}</span></p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="pk-border">
            <h3>Win Ratio</h3>
            <div class="flex-wrapper">
                <div class="global-stats-container">
                    {% for player in top_5_win_ratio %}
                        <p>{{ player.first_name }} {{ player.last_name }}: <span>{{ player.get_win_ratio }}%</span></p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="pk-border">
            <h3>This Year at a Glance</h3>
            <div class="flex-wrapper">
                <div class="global-stats-container">
                    <p>Total Games: <span class="block">{{ this_years_game_count }}</span></p>
                </div>
            </div>
        </div>
    </div>

    <div class="leaderboard pk-border flex-wrapper">
        <div class="league">
            <h2>Champions League</h2>
            <ul>
                {% for player in players|slice:":4" %}
                    <li class="player-card">
                        <p>{{ player.get_form_emoji }} {{ player.first_name }}{% if player.nickname %} <span>"{{ player.nickname }}"</span> {% endif %} {{ player.last_name }}</p>
                        <p class="game-info">(P{{ player.get_this_years_games_played }} RU{{ player.get_this_years_runner_ups }}) <span class="win-count">{{ player.get_this_years_wins }}</span></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="league">
            <h2>Premier League</h2>
            <ul>
                {% for player in players|slice:"4:8" %}
                    <li class="player-card">
                        <p>{{ player.get_form_emoji }} {{ player.first_name }}{% if player.nickname %} <span>"{{ player.nickname }}"</span> {% endif %} {{ player.last_name }}</p>
                        <p class="game-info">(P{{ player.get_this_years_games_played }} RU{{ player.get_this_years_runner_ups }}) <span class="win-count">{{ player.get_this_years_wins }}</span></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="league">
            <h2>Championship</h2>
            <ul>
                {% for player in players|slice:"8:12" %}
                    <li class="player-card">
                        <p>{{ player.get_form_emoji }} {{ player.first_name }}{% if player.nickname %} <span>"{{ player.nickname }}"</span> {% endif %} {{ player.last_name }}</p>
                        <p class="game-info">(P{{ player.get_this_years_games_played }} RU{{ player.get_this_years_runner_ups }}) <span class="win-count">{{ player.get_this_years_wins }}</span></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="league">
            <h2>Vanarama</h2>
            <ul>
                {% for player in players|slice:"12:16" %}
                    <li class="player-card">
                        <p>{{ player.get_form_emoji }} {{ player.first_name }}{% if player.nickname %} <span>"{{ player.nickname }}"</span> {% endif %} {{ player.last_name }}</p>
                        <p class="game-info">(P{{ player.get_this_years_games_played }} RU{{ player.get_this_years_runner_ups }}) <span class="win-count">{{ player.get_this_years_wins }}</span></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    {% for player in players %}
        <aside class="sidebar">
            <a href="#" class="button-close">&times;</a>
            <div class="sidebar-wrapper">
                <h3>{{ player.first_name }} {{ player.last_name }}</h3>
                <ul class="statisitics-wrapper">
                    <li><p>Wins: <span>{{ player.get_this_years_wins }}</span></p></li>
                    <li><p>Runner Ups: <span>{{ player.get_this_years_runner_ups }}</span></p></li>
                    <li><p>Games Played: <span>{{ player.get_this_years_games_played }}</span></p></li>
                    <li><p>Percentage of Games Played: <span>{{ player.get_this_years_games_played_percentage }}%</span></p></li>
                    
                    <li class="mt-36"><p>Last Played: <span>{{ player.get_last_game_played }}</span></p></li>
                    <li><p>Last Win: <span>{{ player.get_last_win }}</span></p></li>
                    <li><p>Predicted Wins: <span>{{ player.get_predicted_wins }}</span></p></li>
                    <li><p>Win Ratio: <span>{{ player.get_win_ratio }}%</span></p></li>
                    
                    <li class="mt-36"><p>All-time Wins: <span>{{ player.get_total_points }}</span></p></li>
                    <li><p>All-time Games Played: <span>{{ player.games_played.count }}</span></p></li>
                    <!--<li><p>Longest Win Streak: <span>[ Streak ]</span></p></li>-->
                </ul>
                <div class="form">
                    <h4>Current Form: {{ player.get_form_score|floatformat:1 }}</h4>
                    <div class="form-labels flex-wrapper">
                        <p class="white-text m-0">Oldest</p>
                        <p class="white-text m-0">Most Recent</p>
                    </div>
                    <ul class="form-wrapper">
                        {% for key, value in player.get_form.items %}
                        <li class="{{ value }}"><span></span></li>
                        {% endfor %}
                    </ul>
                </div>
                <!--
                <div class="wins">
                    <h4>Killer League Wins</h4>
                    <ul class="wins-wrapper">
                        <li>2023</li>
                    </ul>
                </div>
                -->
            </div>
        </aside>
    {% endfor %}

    <div class="views flex-wrapper">
        <div class="monthly-leaders pk-border">
            <h3>Monthly Top 3</h3>
            <ul>
                {% for player in monthly_leaders %}
                    <li class="player-card">
                        <p>{{ player.first_name }} {{ player.last_name }}</p>
                        <p class="game-info"><span class="win-count">{{ player.get_this_months_wins }}</span></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    
        <div class="weekly-leaders pk-border">
            <h3>Weekly Top 3</h3>
            <ul>
                {% for player in weekly_leaders %}
                    <li class="player-card">
                        <p>{{ player.first_name }} {{ player.last_name }}</p>
                        <p class="game-info"><span class="win-count">{{ player.get_this_weeks_wins }}</span></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="sessions-wrapper">
        <p class="white-text">You have visited the Darts Portal {{ request.session.visit_count }} time{{ request.session.visit_count|pluralize }}</p>
    </div>
{% endblock content %}