config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('darts.urls', namespace='darts')),
    path('players/', include('users.urls')),

    path('__debug__/', include("debug_toolbar.urls")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

darts/urls.py
from django.urls import path

from . import views
from .views import LeagueTableView, WinCreateView, AllGamesView, AllResults, SubmitGameView

app_name = 'darts'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('all-games/', AllResults.as_view(), name='all_games'),
    path('submit-game/', SubmitGameView.as_view(), name='submit_game'),
    path('wrapped/<int:year>/', views.wrapped, name='wrapped'),

    # Old URLs
    path('old/', LeagueTableView.as_view(), name='dashboard_old'),
    path('old/all-games/', AllGamesView.as_view(), name='all_games_old'),
    path('old/submit-win/', WinCreateView.as_view(), name='submit_win_old'),
]

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="noindex">
        <link rel="icon" href="{% static 'images/favicon.png' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <title>{% block title %}Darts Portal{% endblock title %}</title>
    </head>
    <body class="p-0 bg-transparent">
        <header>
            <div class="primary-container">
                <nav class="flex-wrapper">
                    <div class="menu-container">
                        <a href="{% url 'darts:dashboard' %}" class="logo" title="Home">
                            <img src="{% static 'images/favicon.png' %}" alt="Pixel Kicks">
                        </a>
                        <ul class="menu m-0 p-0">
                            <li><a href="{% url 'darts:dashboard' %}" title="Leaderboard">Leaderboard</a></li>
                            <li><a href="{% url 'darts:all_games' %}" title="All Results">All Results</a></li>
                        </ul>
                    </div>
                    <div class="actions-container">
                        <a href="{% url 'darts:submit_game' %}" class="button desktop" title="Submit Win">Submit a Game</a>
                        <a href="#" class="button mobile" title="Mobile Menu">Menu</a>
                    </div>
                </nav>
            </div>
        </header>
        <main>
            <section class="title-section">
                <div class="primary-container">
                    {% block heading %}{% endblock heading %}
                </div>
            </section>
            {% block main %}{% endblock main %}
        </main>
        <aside>
            {% block sidebar %}{% endblock sidebar %}
        </aside>
        <footer></footer>
    </body>

    <script src="{% static 'js/script.js' %}"></script>
    {% block scripts %}{% endblock scripts %}
</html>

templates/_new_base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'images/favicon.png' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <title>{% block title %}Darts Portal{% endblock title %}</title>
    </head>
    <body class="p-0 bg-transparent">
        <header>
            <div class="primary-container">
                <nav class="flex-wrapper">
                    <div class="menu-container">
                        <a href="{% url 'darts:home' %}" class="logo" title="Home">
                            <img src="{% static 'images/favicon.png' %}" alt="Pixel Kicks">
                        </a>
                        <ul class="menu m-0 p-0">
                            <li><a href="{% url 'darts:home' %}" title="Leaderboard">Killer Leaderboard</a></li>
                            <li><a href="{% url 'darts:all_games' %}" title="Leaderboard">All Results</a></li>
                            <li><a href="{% url 'darts:bets' %}" title="Leaderboard">Bets</a></li>
                        </ul>
                    </div>
                    <div class="actions-container">
                        <a href="{% url 'darts:submit_win' %}" class="button desktop" title="Submit Win">Submit a Game</a>
                        <a href="#" class="button mobile" title="Mobile Menu">Menu</a>
                    </div>
                </nav>
            </div>
        </header>
        <main>
            <section class="title-section-new">
                <div class="primary-container">
                    {% block heading %}{% endblock heading %}
                </div>
            </section>
            {% block stats %}{% endblock stats %}
        </main>
        <footer></footer>
    </body>
</html>

templates/all_games.html
{% extends '_base.html' %}

{% block title %}Darts Portal | All Killer Results{% endblock title %}

{% block content %}
    <div class="title-section">
        <h1>All Killer Results</h1>
    </div>

    <div class="all-games">
        <table>
            <thead>
                <tr>
                    <th>
                        <h3>Date</h3>
                    </th>
                    <th>
                        <h3>Winner</h3>
                    </th>
                    <th>
                        <h3>Runner Up</h3>
                    </th>
                    <th class="align-left">
                        <h3>Losers</h3>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for game in all_games %}
                    <tr>
                        <td class="narrow"><p>{{ game.date|date:"D d M" }}</p></td>
                        <td class="narrow"><p>{{ game.winner.first_name }} {{ game.winner.last_name }}</p></td>
                        <td class="narrow"><p>{{ game.runner_up.first_name }} {{ game.runner_up.last_name }}</p></td>
                        <td class="align-left">
                            <p>
                                {% for loser in game.participants.all %}
                                    {% if loser.pk != game.winner.pk and loser.pk != game.runner_up.pk %}
                                        <span>{{ loser.first_name }} {{ loser.last_name }}, </span>
                                    {% endif %}
                                {% endfor %}
                            </p>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock content %}

templates/create_win.html
{% extends '_base.html' %}

{% block title %}Darts Portal | Submit a Game{% endblock title %}

{% block content %}
    <div class="title-section">
        <h1>Submit a Game</h1>
        <p>Last game submitted on: {{ last_result.0.date|date:"l j F Y" }}</p>
    </div>
    <section class="win-form pk-border">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="button" value="Save">
        </form>
    </section>
{% endblock content %}

templates/dashboard.html
{% extends '_new_base.html' %}

{% block heading %}
    <div class="flex-wrapper align-center">
        <h1>Leaderboard</h1>
        <p class="white-text m-0">You have visited the Darts Portal {{ visit_count }} time{{ visit_count|pluralize }}</p>
    </div>
{% endblock heading %}

{% block stats %}
    <section class="stats-section">
        <div class="primary-container">
            <div class="flex-wrapper align-stretch">
                <div class="stats-container full-width">
                    <div class="span">
                        <h3>{{ last_result.0.date|date:"l j F" }}</h3>
                        <div class="flex-wrapper">
                            <div class="global-stats-container">
                                <p>Winner: <span>{{ last_result.0.winner.first_name }} {{ last_result.0.winner.last_name }}</span></p>
                                <p>Runner Up: <span>{{ last_result.0.runner_up.first_name }} {{ last_result.0.runner_up.last_name }}</span></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="stats-container full-width">
                    <div class="span">
                        <h3>Current Form</h3>
                        <div class="flex-wrapper">
                            <div class="global-stats-container">
                                {% for player in top_5_form %}
                                    <p>{{ player.first_name }} {{ player.last_name }}: <span>{{ player.get_form_score|floatformat:1 }}</span></p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="stats-container full-width">
                    <div class="span">
                        <h3>Win Ratio</h3>
                        <div class="flex-wrapper">
                            <div class="global-stats-container">
                                {% for player in top_5_win_ratio %}
                                    <p>{{ player.first_name }} {{ player.last_name }}: <span>{{ player.get_win_ratio }}%</span></p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="stats-container full-width">
                    <div class="span">
                        <h3>This Year at a Glance</h3>
                        <div class="flex-wrapper">
                            <div class="global-stats-container">
                                <p class="white-text">Total Games: <span class="block">{{ this_years_game_count }}</span></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="stats-section">
        <div class="primary-container">
            <div class="stats-container">
                <div class="flex-wrapper">
                    <div class="league">
                        <h2>Champions League</h2>
                        <ul class="m-0">
                            {% for player in players|slice:":4" %}
                                <li class="player-card">
                                    <p>{{ player.get_form_emoji }} {{ player.first_name }}{% if player.nickname %} <span>"{{ player.nickname }}"</span> {% endif %} {{ player.last_name }}</p>
                                    <p class="game-info">(P{{ player.get_this_years_games_played }} RU{{ player.get_this_years_runner_ups }}) <span class="win-count">{{ player.get_this_years_wins }}</span></p>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="league">
                        <h2>Premier League</h2>
                        <ul class="m-0">
                            {% for player in players|slice:"4:8" %}
                                <li class="player-card">
                                    <p>{{ player.get_form_emoji }} {{ player.first_name }}{% if player.nickname %} <span>"{{ player.nickname }}"</span> {% endif %} {{ player.last_name }}</p>
                                    <p class="game-info">(P{{ player.get_this_years_games_played }} RU{{ player.get_this_years_runner_ups }}) <span class="win-count">{{ player.get_this_years_wins }}</span></p>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="league">
                        <h2>Championship</h2>
                        <ul class="m-0">
                            {% for player in players|slice:"8:12" %}
                                <li class="player-card">
                                    <p>{{ player.get_form_emoji }} {{ player.first_name }}{% if player.nickname %} <span>"{{ player.nickname }}"</span> {% endif %} {{ player.last_name }}</p>
                                    <p class="game-info">(P{{ player.get_this_years_games_played }} RU{{ player.get_this_years_runner_ups }}) <span class="win-count">{{ player.get_this_years_wins }}</span></p>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="league">
                        <h2>Vanarama</h2>
                        <ul class="m-0">
                            {% for player in players|slice:"12:16" %}
                                <li class="player-card">
                                    <p>{{ player.get_form_emoji }} {{ player.first_name }}{% if player.nickname %} <span>"{{ player.nickname }}"</span> {% endif %} {{ player.last_name }}</p>
                                    <p class="game-info">(P{{ player.get_this_years_games_played }} RU{{ player.get_this_years_runner_ups }}) <span class="win-count">{{ player.get_this_years_wins }}</span></p>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="stats-section">
        <div class="primary-container">
            <div class="flex-wrapper align-stretch">
                <div class="stats-container full-width">
                    <div class="span">
                        <h3>Monthly Top 3</h3>
                        <ul>
                            {% for player in monthly_leaders %}
                                <li class="player-card">
                                    <p>{{ player.first_name }} {{ player.last_name }}</p>
                                    <p class="game-info"><span class="win-count">{{ player.get_this_months_wins }}</span></p>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="stats-container full-width">
                    <div class="span">
                        <h3>Weekly Top 3</h3>
                        <ul>
                            {% for player in weekly_leaders %}
                                <li class="player-card">
                                    <p>{{ player.first_name }} {{ player.last_name }}</p>
                                    <p class="game-info"><span class="win-count">{{ player.get_this_weeks_wins }}</span></p>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock stats %}

templates/index.html
{% extends '_base.html' %}

{% block title %}Darts Portal{% endblock title %}

{% block content %}
    <div class="title-section">
        <h1>Killer Darts Leaderboard</h1>
        <div class="buttons">
            <a href="{% url 'darts:submit_win' %}" class="button" title="Submit Win">Submit a Game</a>
        </div>
    </div>

    <div class="killer-stats">
        <div class="pk-border">
            <h3>{{ last_result.0.date|date:"l j F" }}</h3>
            <div class="flex-wrapper">
                <div class="global-stats-container">
                    <p>Winner: <span>{{ last_result.0.winner.first_name }} {{ last_result.0.winner.last_name }}</span></p>
                    <p>Runner Up: <span>{{ last_result.0.runner_up.first_name }} {{ last_result.0.runner_up.last_name }}</span></p>
                </div>
            </div>
        </div>
        <div class="pk-border">
            <h3>Current Form</h3>
            <div class="flex-wrapper">
                <div class="global-stats-container">
                    {% for player in top_5_form %}
                        <p>{{ player.first_name }} {{ player.last_name }}: <span>{{ player.get_form_score|floatformat:1 }}</span></p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="pk-border">
            <h3>Win Ratio</h3>
            <div class="flex-wrapper">
                <div class="global-stats-container">
                    {% for player in top_5_win_ratio %}
                        <p>{{ player.first_name }} {{ player.last_name }}: <span>{{ player.get_win_ratio }}%</span></p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="pk-border">
            <h3>This Year at a Glance</h3>
            <div class="flex-wrapper">
                <div class="global-stats-container">
                    <p>Total Games: <span class="block">{{ this_years_game_count }}</span></p>
                </div>
            </div>
        </div>
    </div>

    <div class="leaderboard pk-border flex-wrapper">
        <div class="league">
            <h2>Champions League</h2>
            <ul>
                {% for player in players|slice:":4" %}
                    <li class="player-card">
                        <p>{{ player.get_form_emoji }} {{ player.first_name }}{% if player.nickname %} <span>"{{ player.nickname }}"</span> {% endif %} {{ player.last_name }}</p>
                        <p class="game-info">(P{{ player.get_this_years_games_played }} RU{{ player.get_this_years_runner_ups }}) <span class="win-count">{{ player.get_this_years_wins }}</span></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="league">
            <h2>Premier League</h2>
            <ul>
                {% for player in players|slice:"4:8" %}
                    <li class="player-card">
                        <p>{{ player.get_form_emoji }} {{ player.first_name }}{% if player.nickname %} <span>"{{ player.nickname }}"</span> {% endif %} {{ player.last_name }}</p>
                        <p class="game-info">(P{{ player.get_this_years_games_played }} RU{{ player.get_this_years_runner_ups }}) <span class="win-count">{{ player.get_this_years_wins }}</span></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="league">
            <h2>Championship</h2>
            <ul>
                {% for player in players|slice:"8:12" %}
                    <li class="player-card">
                        <p>{{ player.get_form_emoji }} {{ player.first_name }}{% if player.nickname %} <span>"{{ player.nickname }}"</span> {% endif %} {{ player.last_name }}</p>
                        <p class="game-info">(P{{ player.get_this_years_games_played }} RU{{ player.get_this_years_runner_ups }}) <span class="win-count">{{ player.get_this_years_wins }}</span></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="league">
            <h2>Vanarama</h2>
            <ul>
                {% for player in players|slice:"12:16" %}
                    <li class="player-card">
                        <p>{{ player.get_form_emoji }} {{ player.first_name }}{% if player.nickname %} <span>"{{ player.nickname }}"</span> {% endif %} {{ player.last_name }}</p>
                        <p class="game-info">(P{{ player.get_this_years_games_played }} RU{{ player.get_this_years_runner_ups }}) <span class="win-count">{{ player.get_this_years_wins }}</span></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    {% for player in players %}
        <aside class="sidebar">
            <a href="#" class="button-close">&times;</a>
            <div class="sidebar-wrapper">
                <h3>{{ player.first_name }} {{ player.last_name }}</h3>
                <ul class="statisitics-wrapper">
                    <li><p>Wins: <span>{{ player.get_this_years_wins }}</span></p></li>
                    <li><p>Runner Ups: <span>{{ player.get_this_years_runner_ups }}</span></p></li>
                    <li><p>Games Played: <span>{{ player.get_this_years_games_played }}</span></p></li>
                    <li><p>Percentage of Games Played: <span>{{ player.get_this_years_games_played_percentage }}%</span></p></li>
                    
                    <li class="mt-36"><p>Last Played: <span>{{ player.get_last_game_played }}</span></p></li>
                    <li><p>Last Win: <span>{{ player.get_last_win }}</span></p></li>
                    <li><p>Predicted Wins: <span>{{ player.get_predicted_wins }}</span></p></li>
                    <li><p>Win Ratio: <span>{{ player.get_win_ratio }}%</span></p></li>
                    
                    <li class="mt-36"><p>All-time Wins: <span>{{ player.get_total_points }}</span></p></li>
                    <li><p>All-time Games Played: <span>{{ player.games_played.count }}</span></p></li>
                    <!--<li><p>Longest Win Streak: <span>[ Streak ]</span></p></li>-->
                </ul>
                <div class="form">
                    <h4>Current Form: {{ player.get_form_score|floatformat:1 }}</h4>
                    <div class="form-labels flex-wrapper">
                        <p class="white-text m-0">Oldest</p>
                        <p class="white-text m-0">Most Recent</p>
                    </div>
                    <ul class="form-wrapper">
                        {% for key, value in player.get_form.items %}
                        <li class="{{ value }}"><span></span></li>
                        {% endfor %}
                    </ul>
                </div>
                <!--
                <div class="wins">
                    <h4>Killer League Wins</h4>
                    <ul class="wins-wrapper">
                        <li>2023</li>
                    </ul>
                </div>
                -->
            </div>
        </aside>
    {% endfor %}

    <div class="views flex-wrapper">
        <div class="monthly-leaders pk-border">
            <h3>Monthly Top 3</h3>
            <ul>
                {% for player in monthly_leaders %}
                    <li class="player-card">
                        <p>{{ player.first_name }} {{ player.last_name }}</p>
                        <p class="game-info"><span class="win-count">{{ player.get_this_months_wins }}</span></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    
        <div class="weekly-leaders pk-border">
            <h3>Weekly Top 3</h3>
            <ul>
                {% for player in weekly_leaders %}
                    <li class="player-card">
                        <p>{{ player.first_name }} {{ player.last_name }}</p>
                        <p class="game-info"><span class="win-count">{{ player.get_this_weeks_wins }}</span></p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="sessions-wrapper">
        <p class="white-text">You have visited the Darts Portal {{ request.session.visit_count }} time{{ request.session.visit_count|pluralize }}</p>
    </div>
{% endblock content %}